### PR TITLE
Add option when solving problem to optimize with default metric

### PR DESCRIPTION
**Pull request by alexander-sung**
In the past, it was possible to call a `OneshotPlanner()` with parameter `optimality_guarantee=OptimalityGuarantee.SOLVED_OPTIMALLY` without providing any metric. This has been changed in UP. For most basic sequential planning problems without action costs, however, it seems rather clear what metric to use. This pull request adds the option to use the `MinimizeSequentialPlanLength` metric by default.

### CODE REVIEW

**Comment by alexander-sung** [comment]
Dear @franklinselva, does this change work for you or does it interfere with temporal planning?

@sebastianstock, for your information.

**Comment by franklinselva** [comment]
@alexander-sung Currently, `Bridge().solve()` expects sequential plans by default. I think using the function to solve temporal planning might crash.

Also, we may need to revise the `solve()` function since dependency graphs can be now used as default way for execution.

**Comment by franklinselva** [comment]
On my side, the changes work well with temporal planning.

**Comment by alexander-sung** [comment]
Yes, I'm referring to your second point. The function name `solve()` is very unspecific, so you might want to use this interface for more than sequential plans, I thought. We can discuss this further in our next meeting.

**Pull request merged**
